services:
  mongodb:
    image: mongo:7
    container_name: dms_mongodb
    restart: always
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: dms_server
    restart: always
    ports:
      - "5051:5051"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: dms_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo_data: